[target.aarch64-linux-android]
linker = "./third_party/android_ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android21-clang++"
[target.armv7-unknown-linux-musleabihf]
linker = "./third_party/toolchain/armv7-linux-musl-eabihf/bin/arm-linux-musleabihf-gcc"
[target.armv7-unknown-linux-gnueabihf]
linker = "./third_party/toolchain/armv7-linux-gnueabihf/bin/arm-linux-gnueabihf-gcc"
